// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFTF3F-o8fx5u9qrOFW8qv-g7PhdxPFwc',
    appId: '1:557542203018:web:0a2c6c62e84e2adc3cd773',
    messagingSenderId: '557542203018',
    projectId: 'store-ad-min-app',
    authDomain: 'store-ad-min-app.firebaseapp.com',
    databaseURL: 'https://store-ad-min-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'store-ad-min-app.appspot.com',
    measurementId: 'G-XJRE9L7CZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnT6Et2UWaLAe8L5A4NNSO_k-ApPDhM74',
    appId: '1:557542203018:android:20501ced546178543cd773',
    messagingSenderId: '557542203018',
    projectId: 'store-ad-min-app',
    databaseURL: 'https://store-ad-min-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'store-ad-min-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo85mkfKMnLeyHbqmRG_PbXPO75-PtroU',
    appId: '1:557542203018:ios:53467ed5299432633cd773',
    messagingSenderId: '557542203018',
    projectId: 'store-ad-min-app',
    databaseURL: 'https://store-ad-min-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'store-ad-min-app.appspot.com',
    androidClientId: '557542203018-k7cjipo0ngd8o5aqpkmvgcj4j6u43mgc.apps.googleusercontent.com',
    iosClientId: '557542203018-dthg867el16fsg21gsb6i75qnk23earf.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeAdminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo85mkfKMnLeyHbqmRG_PbXPO75-PtroU',
    appId: '1:557542203018:ios:1f07f4e510166b983cd773',
    messagingSenderId: '557542203018',
    projectId: 'store-ad-min-app',
    databaseURL: 'https://store-ad-min-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'store-ad-min-app.appspot.com',
    androidClientId: '557542203018-k7cjipo0ngd8o5aqpkmvgcj4j6u43mgc.apps.googleusercontent.com',
    iosClientId: '557542203018-ao9j2719nk2er1nrcutd0ml5f6elmsdf.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeAdminApp.RunnerTests',
  );
}
